---


- name: Install IIS
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes

#- name: Pre-reqs for ansible to run
#  hosts: all
#  gather_facts: false
#  become: yes
#  pre_tasks:
#    - raw: test -e /usr/bin/python || ( apt -y update && apt install -y python-minimal)
#
#- name: Build
#  hosts: all
#  become: yes
#  tasks:
#    - name: nginx
#      apt:
#        name: nginx
#        state: present
#
#    - service:
#        name: nginx
#        enabled: yes
#        state: started
#
#- name: Test what was installed
#  hosts: all
#  tasks:
#    - name: test nginx
#      shell: curl -v localhost