---


- name: Install IIS
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes


- name: Test what was installed
  hosts: all
  gather_facts: false
  tasks:
    - name: Test
      win_uri:
        url: http://localhost
